// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuevMfDyxVn3s6TrL4nJ6zci685NXzwOM',
    appId: '1:426253093170:web:f46c12ee6764347009ef2b',
    messagingSenderId: '426253093170',
    projectId: 'my-portfolio-53297',
    authDomain: 'my-portfolio-53297.firebaseapp.com',
    storageBucket: 'my-portfolio-53297.firebasestorage.app',
    measurementId: 'G-X301QCC0QM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi6tO_XSYX83eOTbcpWGT5ZA4o2Zs0M8A',
    appId: '1:426253093170:android:9668f6e92756399d09ef2b',
    messagingSenderId: '426253093170',
    projectId: 'my-portfolio-53297',
    storageBucket: 'my-portfolio-53297.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXQBXr4EkN0FTk7FheKNkUdh-HG5AJ5js',
    appId: '1:426253093170:ios:02d878fce82f776409ef2b',
    messagingSenderId: '426253093170',
    projectId: 'my-portfolio-53297',
    storageBucket: 'my-portfolio-53297.firebasestorage.app',
    iosBundleId: 'com.example.myPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXQBXr4EkN0FTk7FheKNkUdh-HG5AJ5js',
    appId: '1:426253093170:ios:02d878fce82f776409ef2b',
    messagingSenderId: '426253093170',
    projectId: 'my-portfolio-53297',
    storageBucket: 'my-portfolio-53297.firebasestorage.app',
    iosBundleId: 'com.example.myPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuevMfDyxVn3s6TrL4nJ6zci685NXzwOM',
    appId: '1:426253093170:web:420a7901d2701c9e09ef2b',
    messagingSenderId: '426253093170',
    projectId: 'my-portfolio-53297',
    authDomain: 'my-portfolio-53297.firebaseapp.com',
    storageBucket: 'my-portfolio-53297.firebasestorage.app',
    measurementId: 'G-K4DZC5FQK3',
  );
}
